export const CREATE_PROFILE_ACTION = "CREATE_PROFILE_ACTION";
export const UPDATE_PROFILE_ACTION = "UPDATE_PROFILE_ACTION";
export const GET_USER_ACTION = "GET_USER_ACTION";
export const GET_USERINFO_ACTION = "GET_USERINFO_ACTION";
export const GET_REPOINFO_ACTION = "GET_REPOINFO_ACTION";
export const SET_AUTHPROFILE_ACTION = "SET_AUTHPROFILE_ACTION";
